apiVersion: apps/v1
kind: Deployment
metadata:
   name: emptydorectoryvolume
spec:
   replicas: 3
   strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 2
       maxUnavailable: 0
   selector:
     matchLabels:
       env: dev
   template:
        metadata:
          labels:
            env: dev
        spec:
           containers:
             - name: learnvolume
               image: nginx
               ports:
                 - containerPort: 80
               volumeMounts:
                - mountPath: "/usr/share/nginx/html"
                  name: myvolume
           containers:
             - name: phpcontvolume
               image: php
               ports:
                 - containerPort: 1000
               volumeMounts:
                - mountPath: "/usr/share/nginx/html"
                  name: myvolume
           volumes:
             - name: myvolume
               emptyDir: {}
