apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: myreplicaset
spec:
  replicas: 5
  selector:
   matchLabels:
      env: dev
  template:
       metadata:
          labels:
              env: dev
       spec:
            containers:
                 - name: nginxcontaine
                   image: nginx
                   ports:
                     - containerPort: 80
