apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: daemonset
    labels:
       app: promi
spec:
   selector:
       matchLabels:
        app: promi
   template:
     metadata:
         labels:
            app: promi
     spec:
       containers:
         - name: daemonwala
           image: influxdb
           ports:
             - containerPort: 80
