apiVersion: apps/v1
kind: Deployment
metadata:
   name: learningautoscaling
spec:
  replicas: 1
  strategy:
     type: RollingUpdate
     rollingUpdate:
         maxSurge: 2
         maxUnavailable: 0
  selector:
   matchLabels:
      env: dev
  template:
       metadata:
          labels:
              env: dev
       spec:
            containers:
                 - name: nginxcontaine
                   image: nginx
                   ports:
                     - containerPort: 80
                   resources:
                         requests:
                           cpu: "100m"
                         limits:
                           cpu: "500m"
